---
layout: post
title: Where in the world?
subtitle: A leaflet map with the places I have flown
tags: [R,maps,leaflet]
linktormd: true
leafletmap: true
output: github_document 
always_allow_html: yes
---


This is a very personal post, where I just show the map of all the places I have traveled by plain



```{r setup, echo=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(global.par = TRUE)
rm(list = ls())

#output: github_document always_allow_html: yes

library(pacman)
rm(list = ls())

source("../pass.R")

library(pacman)
p_load(dplyr,
       jsonlite,
       readxl,
       geosphere,
       leaflet,
       leaflet.extras,
       sf, htmlwidgets,
       webshot)


# Find airports----
myflights <- read_excel("../_data/flights.xlsx")
tosearch = data.frame(toloc = 
                        (sort(append(
                          myflights$start, 
                          myflights$end))),
                      stringsAsFactors = F)

tosearch = tosearch %>% 
  count(toloc) %>% 
  arrange(desc(n)) %>% 
  as.data.frame()

tosearch$tofun = gsub(" ", "+", tosearch$toloc)
tosearch$tofun = ifelse(tosearch$toloc == "San Sebastian",
                        "san+sebastian+es",
                        tosearch$tofun)

airports <- function(place, n = 1, lang = "en") {
  url = paste(
    "http://api.geonames.org/searchJSON?formatted=true&username=",
    GEONAMES_USER,
    "&style=medium&fcode=AIRP&lang=",
    lang,
    "&maxRows=",
    paste(n),
    "&q=",
    place,
    sep = ""
  )
  geonames = fromJSON(url)
  geonames = data.frame(geonames[["geonames"]])
  geonames$search = place
  geonames = geonames %>% select(tofun = search,
                                 toponymName,
                                 countryCode,
                                 long = lng,
                                 lat)
  return(geonames)
}
#Return
for (i in 1:nrow(tosearch)) {
  res = airports(tosearch[i, c("tofun")])
  row.names(res) <- i
  if (i == 1) {
    final = res
  } else {
    final = rbind(final, res)
  }
  rm(res)
}
rm(i)
final$long = as.numeric(final$long)
final$lat = as.numeric(final$lat)

#Some statistics----
#Number times per city----
ndots = left_join(tosearch, final) %>%
  select(name = toloc,
         countryCode,
         Airport = toponymName,
         n,
         long,
         lat)

# Connecting Routes----
connect = myflights %>% count(start, end) %>% arrange(desc(n))
connect = left_join(connect,
                    ndots %>%
                      select(
                        start = name,
                        long_init = long,
                        lat_init = lat
                      ))
connect = left_join(connect,
                    ndots %>%
                      select(
                        end = name,
                        long_end = long,
                        lat_end = lat
                      ))


connectflights = gcIntermediate(
  connect[, c("long_init", "lat_init")],
  connect[, c("long_end", "lat_end")],
  n = 1000,
  breakAtDateLine = T,
  sp = T
)

linessf=st_as_sf(connectflights)
data=st_sf(connect,st_geometry(linessf))
kms=sum((as.numeric(st_length(data))*data$n)/1000)

# Leaflet-----
map <- leaflet(options = leafletOptions(minZoom = 1)) %>%
  addProviderTiles(providers$CartoDB.DarkMatter,
                   options = list(detectRetina = TRUE,
                                  noWrap = TRUE)) %>%
  setView(-3.56948,  40.49181, zoom = 3) %>%
  setMaxBounds(-180,-90, 180, 90) %>%
  addCircles(
    data = ndots,
    lng = ~ long,
    lat = ~ lat,
    weight = 5,
    radius =  sqrt(ndots$n) * 8000,
    popup = ~ name,
    color = "blue",
    group = "Destinations"
  )

map <-
  addPolylines(
    map,
    weight = 2 * sqrt(connect$n),
    data = connectflights,
    opacity = 2*sqrt(connect$n) / 5,
    col = "blue" ,
    group = "Flights"
  )

map <-   addEasyButton(map,
                       easyButton(
                         icon = "fa-globe",
                         title = "Zoom to Level 1",
                         onClick = JS("function(btn, map){ map.setZoom(1); }")
                       ))

map <- addHeatmap(
  map,
  data = ndots,
  intensity = ~ n*10,
  radius = 30,
  max = 10,
  blur = 50,
  group = "Heatmap"
)
map <-   addLayersControl(
  map,
  overlayGroups = c("Destinations", "Flights", "Heatmap"),
  options = layersControlOptions(collapsed = FALSE)
)
map <- hideGroup(map, c("Destinations", "Flights"))
map
```




## `r format(kms, nsmall=1, big.mark=",")` kms. flown so far.



## Top Cities

```{r Cities,echo=FALSE,  warning=FALSE, message=FALSE, tidy='styler'}
names=read.csv("https://raw.githubusercontent.com/dieghernan/Country-Codes-and-International-Organizations/master/outputs/Countrycodes.csv", fileEncoding="latin1")
Cities =inner_join(ndots %>%
                     select(
                       City=name,
                       countryCode,
                       n
                     ), names %>% select(
                       countryCode=ISO_3166_2,
                       Country=NAME.EN,
                       Continent=CONTINENT.EN,
                       Region=SUBREGION.EN
                     ))

knitr::kable(head(Cities %>% select(
  City,
  Country,
  N=n
) %>% filter(City != "Madrid") %>% arrange(desc(N)),10),format = 'markdown')

```

## Top Countries

```{r Countries,echo=FALSE, warning=FALSE, message=FALSE, tidy='styler'}

knitr::kable(head(
  Cities  %>% filter(City != "Madrid") %>%
    select(Country,
           Continent, n) %>% group_by(Country, Continent) %>% summarise(N = sum(n)) %>%
    arrange(desc(N)),
  5),
format = 'markdown')
  
```

## Top Continents

```{r Continents, echo=FALSE, warning=FALSE, message=FALSE, tidy='styler'}

knitr::kable(head(
  Cities  %>% filter(City != "Madrid") %>%
    select(Continent, Region, n) %>% group_by(Continent, Region) %>% summarise(N = sum(n)) %>%
    arrange(desc(N)),
  5
),
format = 'markdown')
```